"""pnr to Allocation

Revision ID: a50f0e82c702
Revises: b1c3825b11a9
Create Date: 2023-12-20 07:30:11.280423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50f0e82c702'
down_revision: Union[str, None] = 'b1c3825b11a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocation', sa.Column('pnr', sa.String(), nullable=True))
    op.add_column('allocation', sa.Column('is_soft_allocation', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_allocation_pnr'), 'allocation', ['pnr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocation_pnr'), table_name='allocation')
    op.drop_column('allocation', 'is_soft_allocation')
    op.drop_column('allocation', 'pnr')
    # ### end Alembic commands ###
