"""create allocation model

Revision ID: b1c3825b11a9
Revises: 4ecb8509214a
Create Date: 2023-12-14 08:29:37.900191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c3825b11a9'
down_revision: Union[str, None] = '4ecb8509214a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bed_id', sa.UUID(), nullable=False),
    sa.Column('reg', sa.String(), nullable=True),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['bed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_id'), 'allocation', ['id'], unique=False)
    op.create_index(op.f('ix_allocation_partner'), 'allocation', ['partner'], unique=False)
    op.create_index(op.f('ix_allocation_reg'), 'allocation', ['reg'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocation_reg'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_partner'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_id'), table_name='allocation')
    op.drop_table('allocation')
    # ### end Alembic commands ###
