"""[remove] unwanted fields - name, max_count

Revision ID: b72a0ac84cb1
Revises: a50f0e82c702
Create Date: 2023-12-20 14:17:36.745494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b72a0ac84cb1'
down_revision: Union[str, None] = 'a50f0e82c702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bed_name', table_name='bed')
    op.drop_column('bed', 'name')
    op.drop_column('dorm', 'type')
    op.drop_column('room', 'max_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('max_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dorm', sa.Column('type', postgresql.ENUM('east_bunk_bed', 'north_ground_floor_wooden_bed', 'south_bunk_bed', name='type'), autoincrement=False, nullable=False))
    op.add_column('bed', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_bed_name', 'bed', ['name'], unique=False)
    # ### end Alembic commands ###
