"""[fix] ENUM Room.FLOORS

Revision ID: f88b83f9ce71
Revises: b72a0ac84cb1
Create Date: 2023-12-20 15:22:09.888021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88b83f9ce71'
down_revision: Union[str, None] = 'b72a0ac84cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE floor ADD VALUE 'sf'")
    op.execute("ALTER TYPE floor ADD VALUE 'tf'")
    op.execute("ALTER TABLE room ALTER COLUMN floor TYPE floor USING floor::text::floor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
